#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ql_quancafe")]
	public partial class DB_qlQuanCafeDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblBan(tblBan instance);
    partial void UpdatetblBan(tblBan instance);
    partial void DeletetblBan(tblBan instance);
    partial void InserttblThucDon(tblThucDon instance);
    partial void UpdatetblThucDon(tblThucDon instance);
    partial void DeletetblThucDon(tblThucDon instance);
    partial void InserttblCongThuc(tblCongThuc instance);
    partial void UpdatetblCongThuc(tblCongThuc instance);
    partial void DeletetblCongThuc(tblCongThuc instance);
    partial void InserttblChiTietHD(tblChiTietHD instance);
    partial void UpdatetblChiTietHD(tblChiTietHD instance);
    partial void DeletetblChiTietHD(tblChiTietHD instance);
    partial void InserttblHoaDon(tblHoaDon instance);
    partial void UpdatetblHoaDon(tblHoaDon instance);
    partial void DeletetblHoaDon(tblHoaDon instance);
    partial void InserttblLoaiMon(tblLoaiMon instance);
    partial void UpdatetblLoaiMon(tblLoaiMon instance);
    partial void DeletetblLoaiMon(tblLoaiMon instance);
    partial void InserttblLoaiNhanVien(tblLoaiNhanVien instance);
    partial void UpdatetblLoaiNhanVien(tblLoaiNhanVien instance);
    partial void DeletetblLoaiNhanVien(tblLoaiNhanVien instance);
    partial void InserttblNguyenLieu(tblNguyenLieu instance);
    partial void UpdatetblNguyenLieu(tblNguyenLieu instance);
    partial void DeletetblNguyenLieu(tblNguyenLieu instance);
    partial void InserttblNhanVien(tblNhanVien instance);
    partial void UpdatetblNhanVien(tblNhanVien instance);
    partial void DeletetblNhanVien(tblNhanVien instance);
    partial void InserttblTaiKhoan(tblTaiKhoan instance);
    partial void UpdatetblTaiKhoan(tblTaiKhoan instance);
    partial void DeletetblTaiKhoan(tblTaiKhoan instance);
    #endregion
		
		public DB_qlQuanCafeDataContext() : 
				base(global::BLL.Properties.Settings.Default.ql_quancafeConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DB_qlQuanCafeDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_qlQuanCafeDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_qlQuanCafeDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB_qlQuanCafeDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblBan> tblBans
		{
			get
			{
				return this.GetTable<tblBan>();
			}
		}
		
		public System.Data.Linq.Table<tblThucDon> tblThucDons
		{
			get
			{
				return this.GetTable<tblThucDon>();
			}
		}
		
		public System.Data.Linq.Table<tblCongThuc> tblCongThucs
		{
			get
			{
				return this.GetTable<tblCongThuc>();
			}
		}
		
		public System.Data.Linq.Table<tblChiTietHD> tblChiTietHDs
		{
			get
			{
				return this.GetTable<tblChiTietHD>();
			}
		}
		
		public System.Data.Linq.Table<tblHoaDon> tblHoaDons
		{
			get
			{
				return this.GetTable<tblHoaDon>();
			}
		}
		
		public System.Data.Linq.Table<tblLoaiMon> tblLoaiMons
		{
			get
			{
				return this.GetTable<tblLoaiMon>();
			}
		}
		
		public System.Data.Linq.Table<tblLoaiNhanVien> tblLoaiNhanViens
		{
			get
			{
				return this.GetTable<tblLoaiNhanVien>();
			}
		}
		
		public System.Data.Linq.Table<tblNguyenLieu> tblNguyenLieus
		{
			get
			{
				return this.GetTable<tblNguyenLieu>();
			}
		}
		
		public System.Data.Linq.Table<tblNhanVien> tblNhanViens
		{
			get
			{
				return this.GetTable<tblNhanVien>();
			}
		}
		
		public System.Data.Linq.Table<tblTaiKhoan> tblTaiKhoans
		{
			get
			{
				return this.GetTable<tblTaiKhoan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblBan")]
	public partial class tblBan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaBan;
		
		private string _TenBan;
		
		private string _TrangThai;
		
		private string _KhuVuc;
		
		private EntitySet<tblHoaDon> _tblHoaDons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBanChanging(int value);
    partial void OnMaBanChanged();
    partial void OnTenBanChanging(string value);
    partial void OnTenBanChanged();
    partial void OnTrangThaiChanging(string value);
    partial void OnTrangThaiChanged();
    partial void OnKhuVucChanging(string value);
    partial void OnKhuVucChanged();
    #endregion
		
		public tblBan()
		{
			this._tblHoaDons = new EntitySet<tblHoaDon>(new Action<tblHoaDon>(this.attach_tblHoaDons), new Action<tblHoaDon>(this.detach_tblHoaDons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaBan
		{
			get
			{
				return this._MaBan;
			}
			set
			{
				if ((this._MaBan != value))
				{
					this.OnMaBanChanging(value);
					this.SendPropertyChanging();
					this._MaBan = value;
					this.SendPropertyChanged("MaBan");
					this.OnMaBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenBan", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenBan
		{
			get
			{
				return this._TenBan;
			}
			set
			{
				if ((this._TenBan != value))
				{
					this.OnTenBanChanging(value);
					this.SendPropertyChanging();
					this._TenBan = value;
					this.SendPropertyChanged("TenBan");
					this.OnTenBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhuVuc", DbType="NVarChar(50)")]
		public string KhuVuc
		{
			get
			{
				return this._KhuVuc;
			}
			set
			{
				if ((this._KhuVuc != value))
				{
					this.OnKhuVucChanging(value);
					this.SendPropertyChanging();
					this._KhuVuc = value;
					this.SendPropertyChanged("KhuVuc");
					this.OnKhuVucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblBan_tblHoaDon", Storage="_tblHoaDons", ThisKey="MaBan", OtherKey="MaBan")]
		public EntitySet<tblHoaDon> tblHoaDons
		{
			get
			{
				return this._tblHoaDons;
			}
			set
			{
				this._tblHoaDons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblHoaDons(tblHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.tblBan = this;
		}
		
		private void detach_tblHoaDons(tblHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.tblBan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblThucDon")]
	public partial class tblThucDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaMon;
		
		private string _TenMon;
		
		private int _MaLoai;
		
		private string _DonViTinh;
		
		private string _DonGia;
		
		private string _HinhAnh;
		
		private string _TuyChonThem;
		
		private System.Nullable<bool> _PhoBien;
		
		private EntitySet<tblCongThuc> _tblCongThucs;
		
		private EntitySet<tblChiTietHD> _tblChiTietHDs;
		
		private EntityRef<tblLoaiMon> _tblLoaiMon;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaMonChanging(int value);
    partial void OnMaMonChanged();
    partial void OnTenMonChanging(string value);
    partial void OnTenMonChanged();
    partial void OnMaLoaiChanging(int value);
    partial void OnMaLoaiChanged();
    partial void OnDonViTinhChanging(string value);
    partial void OnDonViTinhChanged();
    partial void OnDonGiaChanging(string value);
    partial void OnDonGiaChanged();
    partial void OnHinhAnhChanging(string value);
    partial void OnHinhAnhChanged();
    partial void OnTuyChonThemChanging(string value);
    partial void OnTuyChonThemChanged();
    partial void OnPhoBienChanging(System.Nullable<bool> value);
    partial void OnPhoBienChanged();
    #endregion
		
		public tblThucDon()
		{
			this._tblCongThucs = new EntitySet<tblCongThuc>(new Action<tblCongThuc>(this.attach_tblCongThucs), new Action<tblCongThuc>(this.detach_tblCongThucs));
			this._tblChiTietHDs = new EntitySet<tblChiTietHD>(new Action<tblChiTietHD>(this.attach_tblChiTietHDs), new Action<tblChiTietHD>(this.detach_tblChiTietHDs));
			this._tblLoaiMon = default(EntityRef<tblLoaiMon>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMon", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaMon
		{
			get
			{
				return this._MaMon;
			}
			set
			{
				if ((this._MaMon != value))
				{
					this.OnMaMonChanging(value);
					this.SendPropertyChanging();
					this._MaMon = value;
					this.SendPropertyChanged("MaMon");
					this.OnMaMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenMon", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenMon
		{
			get
			{
				return this._TenMon;
			}
			set
			{
				if ((this._TenMon != value))
				{
					this.OnTenMonChanging(value);
					this.SendPropertyChanging();
					this._TenMon = value;
					this.SendPropertyChanged("TenMon");
					this.OnTenMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoai", DbType="Int NOT NULL")]
		public int MaLoai
		{
			get
			{
				return this._MaLoai;
			}
			set
			{
				if ((this._MaLoai != value))
				{
					if (this._tblLoaiMon.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiChanging(value);
					this.SendPropertyChanging();
					this._MaLoai = value;
					this.SendPropertyChanged("MaLoai");
					this.OnMaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonViTinh", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string DonViTinh
		{
			get
			{
				return this._DonViTinh;
			}
			set
			{
				if ((this._DonViTinh != value))
				{
					this.OnDonViTinhChanging(value);
					this.SendPropertyChanging();
					this._DonViTinh = value;
					this.SendPropertyChanged("DonViTinh");
					this.OnDonViTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonGia", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string DonGia
		{
			get
			{
				return this._DonGia;
			}
			set
			{
				if ((this._DonGia != value))
				{
					this.OnDonGiaChanging(value);
					this.SendPropertyChanging();
					this._DonGia = value;
					this.SendPropertyChanged("DonGia");
					this.OnDonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="NVarChar(200)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this.OnHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._HinhAnh = value;
					this.SendPropertyChanged("HinhAnh");
					this.OnHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TuyChonThem", DbType="NVarChar(100)")]
		public string TuyChonThem
		{
			get
			{
				return this._TuyChonThem;
			}
			set
			{
				if ((this._TuyChonThem != value))
				{
					this.OnTuyChonThemChanging(value);
					this.SendPropertyChanging();
					this._TuyChonThem = value;
					this.SendPropertyChanged("TuyChonThem");
					this.OnTuyChonThemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoBien", DbType="Bit")]
		public System.Nullable<bool> PhoBien
		{
			get
			{
				return this._PhoBien;
			}
			set
			{
				if ((this._PhoBien != value))
				{
					this.OnPhoBienChanging(value);
					this.SendPropertyChanging();
					this._PhoBien = value;
					this.SendPropertyChanged("PhoBien");
					this.OnPhoBienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblThucDon_tblCongThuc", Storage="_tblCongThucs", ThisKey="MaMon", OtherKey="MaMon")]
		public EntitySet<tblCongThuc> tblCongThucs
		{
			get
			{
				return this._tblCongThucs;
			}
			set
			{
				this._tblCongThucs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblThucDon_tblChiTietHD", Storage="_tblChiTietHDs", ThisKey="MaMon", OtherKey="MaMon")]
		public EntitySet<tblChiTietHD> tblChiTietHDs
		{
			get
			{
				return this._tblChiTietHDs;
			}
			set
			{
				this._tblChiTietHDs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblLoaiMon_tblThucDon", Storage="_tblLoaiMon", ThisKey="MaLoai", OtherKey="MaLoai", IsForeignKey=true)]
		public tblLoaiMon tblLoaiMon
		{
			get
			{
				return this._tblLoaiMon.Entity;
			}
			set
			{
				tblLoaiMon previousValue = this._tblLoaiMon.Entity;
				if (((previousValue != value) 
							|| (this._tblLoaiMon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblLoaiMon.Entity = null;
						previousValue.tblThucDons.Remove(this);
					}
					this._tblLoaiMon.Entity = value;
					if ((value != null))
					{
						value.tblThucDons.Add(this);
						this._MaLoai = value.MaLoai;
					}
					else
					{
						this._MaLoai = default(int);
					}
					this.SendPropertyChanged("tblLoaiMon");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblCongThucs(tblCongThuc entity)
		{
			this.SendPropertyChanging();
			entity.tblThucDon = this;
		}
		
		private void detach_tblCongThucs(tblCongThuc entity)
		{
			this.SendPropertyChanging();
			entity.tblThucDon = null;
		}
		
		private void attach_tblChiTietHDs(tblChiTietHD entity)
		{
			this.SendPropertyChanging();
			entity.tblThucDon = this;
		}
		
		private void detach_tblChiTietHDs(tblChiTietHD entity)
		{
			this.SendPropertyChanging();
			entity.tblThucDon = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblCongThuc")]
	public partial class tblCongThuc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaMon;
		
		private int _MaNL;
		
		private decimal _HamLuong;
		
		private decimal _Tong;
		
		private EntityRef<tblThucDon> _tblThucDon;
		
		private EntityRef<tblNguyenLieu> _tblNguyenLieu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaMonChanging(int value);
    partial void OnMaMonChanged();
    partial void OnMaNLChanging(int value);
    partial void OnMaNLChanged();
    partial void OnHamLuongChanging(decimal value);
    partial void OnHamLuongChanged();
    partial void OnTongChanging(decimal value);
    partial void OnTongChanged();
    #endregion
		
		public tblCongThuc()
		{
			this._tblThucDon = default(EntityRef<tblThucDon>);
			this._tblNguyenLieu = default(EntityRef<tblNguyenLieu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMon", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaMon
		{
			get
			{
				return this._MaMon;
			}
			set
			{
				if ((this._MaMon != value))
				{
					if (this._tblThucDon.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaMonChanging(value);
					this.SendPropertyChanging();
					this._MaMon = value;
					this.SendPropertyChanged("MaMon");
					this.OnMaMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNL", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaNL
		{
			get
			{
				return this._MaNL;
			}
			set
			{
				if ((this._MaNL != value))
				{
					if (this._tblNguyenLieu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNLChanging(value);
					this.SendPropertyChanging();
					this._MaNL = value;
					this.SendPropertyChanged("MaNL");
					this.OnMaNLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HamLuong", DbType="Decimal(18,3) NOT NULL")]
		public decimal HamLuong
		{
			get
			{
				return this._HamLuong;
			}
			set
			{
				if ((this._HamLuong != value))
				{
					this.OnHamLuongChanging(value);
					this.SendPropertyChanging();
					this._HamLuong = value;
					this.SendPropertyChanged("HamLuong");
					this.OnHamLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tong", DbType="Decimal(18,3) NOT NULL")]
		public decimal Tong
		{
			get
			{
				return this._Tong;
			}
			set
			{
				if ((this._Tong != value))
				{
					this.OnTongChanging(value);
					this.SendPropertyChanging();
					this._Tong = value;
					this.SendPropertyChanged("Tong");
					this.OnTongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblThucDon_tblCongThuc", Storage="_tblThucDon", ThisKey="MaMon", OtherKey="MaMon", IsForeignKey=true)]
		public tblThucDon tblThucDon
		{
			get
			{
				return this._tblThucDon.Entity;
			}
			set
			{
				tblThucDon previousValue = this._tblThucDon.Entity;
				if (((previousValue != value) 
							|| (this._tblThucDon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblThucDon.Entity = null;
						previousValue.tblCongThucs.Remove(this);
					}
					this._tblThucDon.Entity = value;
					if ((value != null))
					{
						value.tblCongThucs.Add(this);
						this._MaMon = value.MaMon;
					}
					else
					{
						this._MaMon = default(int);
					}
					this.SendPropertyChanged("tblThucDon");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNguyenLieu_tblCongThuc", Storage="_tblNguyenLieu", ThisKey="MaNL", OtherKey="MaNL", IsForeignKey=true)]
		public tblNguyenLieu tblNguyenLieu
		{
			get
			{
				return this._tblNguyenLieu.Entity;
			}
			set
			{
				tblNguyenLieu previousValue = this._tblNguyenLieu.Entity;
				if (((previousValue != value) 
							|| (this._tblNguyenLieu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblNguyenLieu.Entity = null;
						previousValue.tblCongThucs.Remove(this);
					}
					this._tblNguyenLieu.Entity = value;
					if ((value != null))
					{
						value.tblCongThucs.Add(this);
						this._MaNL = value.MaNL;
					}
					else
					{
						this._MaNL = default(int);
					}
					this.SendPropertyChanged("tblNguyenLieu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblChiTietHD")]
	public partial class tblChiTietHD : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaHD;
		
		private int _MaMon;
		
		private int _SoLuong;
		
		private decimal _TongTien;
		
		private string _GiamGia;
		
		private EntityRef<tblThucDon> _tblThucDon;
		
		private EntityRef<tblHoaDon> _tblHoaDon;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHDChanging(int value);
    partial void OnMaHDChanged();
    partial void OnMaMonChanging(int value);
    partial void OnMaMonChanged();
    partial void OnSoLuongChanging(int value);
    partial void OnSoLuongChanged();
    partial void OnTongTienChanging(decimal value);
    partial void OnTongTienChanged();
    partial void OnGiamGiaChanging(string value);
    partial void OnGiamGiaChanged();
    #endregion
		
		public tblChiTietHD()
		{
			this._tblThucDon = default(EntityRef<tblThucDon>);
			this._tblHoaDon = default(EntityRef<tblHoaDon>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHD", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaHD
		{
			get
			{
				return this._MaHD;
			}
			set
			{
				if ((this._MaHD != value))
				{
					if (this._tblHoaDon.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHDChanging(value);
					this.SendPropertyChanging();
					this._MaHD = value;
					this.SendPropertyChanged("MaHD");
					this.OnMaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaMon", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaMon
		{
			get
			{
				return this._MaMon;
			}
			set
			{
				if ((this._MaMon != value))
				{
					if (this._tblThucDon.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaMonChanging(value);
					this.SendPropertyChanging();
					this._MaMon = value;
					this.SendPropertyChanged("MaMon");
					this.OnMaMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int NOT NULL")]
		public int SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTien", DbType="Money NOT NULL")]
		public decimal TongTien
		{
			get
			{
				return this._TongTien;
			}
			set
			{
				if ((this._TongTien != value))
				{
					this.OnTongTienChanging(value);
					this.SendPropertyChanging();
					this._TongTien = value;
					this.SendPropertyChanged("TongTien");
					this.OnTongTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiamGia", DbType="NVarChar(50)")]
		public string GiamGia
		{
			get
			{
				return this._GiamGia;
			}
			set
			{
				if ((this._GiamGia != value))
				{
					this.OnGiamGiaChanging(value);
					this.SendPropertyChanging();
					this._GiamGia = value;
					this.SendPropertyChanged("GiamGia");
					this.OnGiamGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblThucDon_tblChiTietHD", Storage="_tblThucDon", ThisKey="MaMon", OtherKey="MaMon", IsForeignKey=true)]
		public tblThucDon tblThucDon
		{
			get
			{
				return this._tblThucDon.Entity;
			}
			set
			{
				tblThucDon previousValue = this._tblThucDon.Entity;
				if (((previousValue != value) 
							|| (this._tblThucDon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblThucDon.Entity = null;
						previousValue.tblChiTietHDs.Remove(this);
					}
					this._tblThucDon.Entity = value;
					if ((value != null))
					{
						value.tblChiTietHDs.Add(this);
						this._MaMon = value.MaMon;
					}
					else
					{
						this._MaMon = default(int);
					}
					this.SendPropertyChanged("tblThucDon");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHoaDon_tblChiTietHD", Storage="_tblHoaDon", ThisKey="MaHD", OtherKey="MaHD", IsForeignKey=true)]
		public tblHoaDon tblHoaDon
		{
			get
			{
				return this._tblHoaDon.Entity;
			}
			set
			{
				tblHoaDon previousValue = this._tblHoaDon.Entity;
				if (((previousValue != value) 
							|| (this._tblHoaDon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblHoaDon.Entity = null;
						previousValue.tblChiTietHDs.Remove(this);
					}
					this._tblHoaDon.Entity = value;
					if ((value != null))
					{
						value.tblChiTietHDs.Add(this);
						this._MaHD = value.MaHD;
					}
					else
					{
						this._MaHD = default(int);
					}
					this.SendPropertyChanged("tblHoaDon");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblHoaDon")]
	public partial class tblHoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaHD;
		
		private System.DateTime _TGVao;
		
		private System.Nullable<System.DateTime> _TGRa;
		
		private int _MaBan;
		
		private int _MaNV;
		
		private string _TrangThai;
		
		private decimal _TongTienTT;
		
		private string _PhuongThucTT;
		
		private EntitySet<tblChiTietHD> _tblChiTietHDs;
		
		private EntityRef<tblBan> _tblBan;
		
		private EntityRef<tblNhanVien> _tblNhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHDChanging(int value);
    partial void OnMaHDChanged();
    partial void OnTGVaoChanging(System.DateTime value);
    partial void OnTGVaoChanged();
    partial void OnTGRaChanging(System.Nullable<System.DateTime> value);
    partial void OnTGRaChanged();
    partial void OnMaBanChanging(int value);
    partial void OnMaBanChanged();
    partial void OnMaNVChanging(int value);
    partial void OnMaNVChanged();
    partial void OnTrangThaiChanging(string value);
    partial void OnTrangThaiChanged();
    partial void OnTongTienTTChanging(decimal value);
    partial void OnTongTienTTChanged();
    partial void OnPhuongThucTTChanging(string value);
    partial void OnPhuongThucTTChanged();
    #endregion
		
		public tblHoaDon()
		{
			this._tblChiTietHDs = new EntitySet<tblChiTietHD>(new Action<tblChiTietHD>(this.attach_tblChiTietHDs), new Action<tblChiTietHD>(this.detach_tblChiTietHDs));
			this._tblBan = default(EntityRef<tblBan>);
			this._tblNhanVien = default(EntityRef<tblNhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHD", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaHD
		{
			get
			{
				return this._MaHD;
			}
			set
			{
				if ((this._MaHD != value))
				{
					this.OnMaHDChanging(value);
					this.SendPropertyChanging();
					this._MaHD = value;
					this.SendPropertyChanged("MaHD");
					this.OnMaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TGVao", DbType="DateTime NOT NULL")]
		public System.DateTime TGVao
		{
			get
			{
				return this._TGVao;
			}
			set
			{
				if ((this._TGVao != value))
				{
					this.OnTGVaoChanging(value);
					this.SendPropertyChanging();
					this._TGVao = value;
					this.SendPropertyChanged("TGVao");
					this.OnTGVaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TGRa", DbType="DateTime")]
		public System.Nullable<System.DateTime> TGRa
		{
			get
			{
				return this._TGRa;
			}
			set
			{
				if ((this._TGRa != value))
				{
					this.OnTGRaChanging(value);
					this.SendPropertyChanging();
					this._TGRa = value;
					this.SendPropertyChanged("TGRa");
					this.OnTGRaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBan", DbType="Int NOT NULL")]
		public int MaBan
		{
			get
			{
				return this._MaBan;
			}
			set
			{
				if ((this._MaBan != value))
				{
					if (this._tblBan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaBanChanging(value);
					this.SendPropertyChanging();
					this._MaBan = value;
					this.SendPropertyChanged("MaBan");
					this.OnMaBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Int NOT NULL")]
		public int MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._tblNhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongTienTT", DbType="Money NOT NULL")]
		public decimal TongTienTT
		{
			get
			{
				return this._TongTienTT;
			}
			set
			{
				if ((this._TongTienTT != value))
				{
					this.OnTongTienTTChanging(value);
					this.SendPropertyChanging();
					this._TongTienTT = value;
					this.SendPropertyChanged("TongTienTT");
					this.OnTongTienTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhuongThucTT", DbType="NChar(50)")]
		public string PhuongThucTT
		{
			get
			{
				return this._PhuongThucTT;
			}
			set
			{
				if ((this._PhuongThucTT != value))
				{
					this.OnPhuongThucTTChanging(value);
					this.SendPropertyChanging();
					this._PhuongThucTT = value;
					this.SendPropertyChanged("PhuongThucTT");
					this.OnPhuongThucTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblHoaDon_tblChiTietHD", Storage="_tblChiTietHDs", ThisKey="MaHD", OtherKey="MaHD")]
		public EntitySet<tblChiTietHD> tblChiTietHDs
		{
			get
			{
				return this._tblChiTietHDs;
			}
			set
			{
				this._tblChiTietHDs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblBan_tblHoaDon", Storage="_tblBan", ThisKey="MaBan", OtherKey="MaBan", IsForeignKey=true)]
		public tblBan tblBan
		{
			get
			{
				return this._tblBan.Entity;
			}
			set
			{
				tblBan previousValue = this._tblBan.Entity;
				if (((previousValue != value) 
							|| (this._tblBan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblBan.Entity = null;
						previousValue.tblHoaDons.Remove(this);
					}
					this._tblBan.Entity = value;
					if ((value != null))
					{
						value.tblHoaDons.Add(this);
						this._MaBan = value.MaBan;
					}
					else
					{
						this._MaBan = default(int);
					}
					this.SendPropertyChanged("tblBan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNhanVien_tblHoaDon", Storage="_tblNhanVien", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public tblNhanVien tblNhanVien
		{
			get
			{
				return this._tblNhanVien.Entity;
			}
			set
			{
				tblNhanVien previousValue = this._tblNhanVien.Entity;
				if (((previousValue != value) 
							|| (this._tblNhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblNhanVien.Entity = null;
						previousValue.tblHoaDons.Remove(this);
					}
					this._tblNhanVien.Entity = value;
					if ((value != null))
					{
						value.tblHoaDons.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(int);
					}
					this.SendPropertyChanged("tblNhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblChiTietHDs(tblChiTietHD entity)
		{
			this.SendPropertyChanging();
			entity.tblHoaDon = this;
		}
		
		private void detach_tblChiTietHDs(tblChiTietHD entity)
		{
			this.SendPropertyChanging();
			entity.tblHoaDon = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblLoaiMon")]
	public partial class tblLoaiMon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaLoai;
		
		private string _TenLoai;
		
		private EntitySet<tblThucDon> _tblThucDons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiChanging(int value);
    partial void OnMaLoaiChanged();
    partial void OnTenLoaiChanging(string value);
    partial void OnTenLoaiChanged();
    #endregion
		
		public tblLoaiMon()
		{
			this._tblThucDons = new EntitySet<tblThucDon>(new Action<tblThucDon>(this.attach_tblThucDons), new Action<tblThucDon>(this.detach_tblThucDons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoai", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaLoai
		{
			get
			{
				return this._MaLoai;
			}
			set
			{
				if ((this._MaLoai != value))
				{
					this.OnMaLoaiChanging(value);
					this.SendPropertyChanging();
					this._MaLoai = value;
					this.SendPropertyChanged("MaLoai");
					this.OnMaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoai", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenLoai
		{
			get
			{
				return this._TenLoai;
			}
			set
			{
				if ((this._TenLoai != value))
				{
					this.OnTenLoaiChanging(value);
					this.SendPropertyChanging();
					this._TenLoai = value;
					this.SendPropertyChanged("TenLoai");
					this.OnTenLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblLoaiMon_tblThucDon", Storage="_tblThucDons", ThisKey="MaLoai", OtherKey="MaLoai")]
		public EntitySet<tblThucDon> tblThucDons
		{
			get
			{
				return this._tblThucDons;
			}
			set
			{
				this._tblThucDons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblThucDons(tblThucDon entity)
		{
			this.SendPropertyChanging();
			entity.tblLoaiMon = this;
		}
		
		private void detach_tblThucDons(tblThucDon entity)
		{
			this.SendPropertyChanging();
			entity.tblLoaiMon = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblLoaiNhanVien")]
	public partial class tblLoaiNhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaLoaiNV;
		
		private string _TenLoaiNV;
		
		private EntitySet<tblNhanVien> _tblNhanViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiNVChanging(int value);
    partial void OnMaLoaiNVChanged();
    partial void OnTenLoaiNVChanging(string value);
    partial void OnTenLoaiNVChanged();
    #endregion
		
		public tblLoaiNhanVien()
		{
			this._tblNhanViens = new EntitySet<tblNhanVien>(new Action<tblNhanVien>(this.attach_tblNhanViens), new Action<tblNhanVien>(this.detach_tblNhanViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiNV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaLoaiNV
		{
			get
			{
				return this._MaLoaiNV;
			}
			set
			{
				if ((this._MaLoaiNV != value))
				{
					this.OnMaLoaiNVChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiNV = value;
					this.SendPropertyChanged("MaLoaiNV");
					this.OnMaLoaiNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiNV", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenLoaiNV
		{
			get
			{
				return this._TenLoaiNV;
			}
			set
			{
				if ((this._TenLoaiNV != value))
				{
					this.OnTenLoaiNVChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiNV = value;
					this.SendPropertyChanged("TenLoaiNV");
					this.OnTenLoaiNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblLoaiNhanVien_tblNhanVien", Storage="_tblNhanViens", ThisKey="MaLoaiNV", OtherKey="MaLoaiNV")]
		public EntitySet<tblNhanVien> tblNhanViens
		{
			get
			{
				return this._tblNhanViens;
			}
			set
			{
				this._tblNhanViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblNhanViens(tblNhanVien entity)
		{
			this.SendPropertyChanging();
			entity.tblLoaiNhanVien = this;
		}
		
		private void detach_tblNhanViens(tblNhanVien entity)
		{
			this.SendPropertyChanging();
			entity.tblLoaiNhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblNguyenLieu")]
	public partial class tblNguyenLieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNL;
		
		private string _TenNL;
		
		private decimal _SoLuong;
		
		private string _DonViTinh;
		
		private System.DateTime _NgayNhap;
		
		private EntitySet<tblCongThuc> _tblCongThucs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNLChanging(int value);
    partial void OnMaNLChanged();
    partial void OnTenNLChanging(string value);
    partial void OnTenNLChanged();
    partial void OnSoLuongChanging(decimal value);
    partial void OnSoLuongChanged();
    partial void OnDonViTinhChanging(string value);
    partial void OnDonViTinhChanged();
    partial void OnNgayNhapChanging(System.DateTime value);
    partial void OnNgayNhapChanged();
    #endregion
		
		public tblNguyenLieu()
		{
			this._tblCongThucs = new EntitySet<tblCongThuc>(new Action<tblCongThuc>(this.attach_tblCongThucs), new Action<tblCongThuc>(this.detach_tblCongThucs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNL", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaNL
		{
			get
			{
				return this._MaNL;
			}
			set
			{
				if ((this._MaNL != value))
				{
					this.OnMaNLChanging(value);
					this.SendPropertyChanging();
					this._MaNL = value;
					this.SendPropertyChanged("MaNL");
					this.OnMaNLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNL", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenNL
		{
			get
			{
				return this._TenNL;
			}
			set
			{
				if ((this._TenNL != value))
				{
					this.OnTenNLChanging(value);
					this.SendPropertyChanging();
					this._TenNL = value;
					this.SendPropertyChanged("TenNL");
					this.OnTenNLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Decimal(18,3) NOT NULL")]
		public decimal SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonViTinh", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DonViTinh
		{
			get
			{
				return this._DonViTinh;
			}
			set
			{
				if ((this._DonViTinh != value))
				{
					this.OnDonViTinhChanging(value);
					this.SendPropertyChanging();
					this._DonViTinh = value;
					this.SendPropertyChanged("DonViTinh");
					this.OnDonViTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayNhap", DbType="Date NOT NULL")]
		public System.DateTime NgayNhap
		{
			get
			{
				return this._NgayNhap;
			}
			set
			{
				if ((this._NgayNhap != value))
				{
					this.OnNgayNhapChanging(value);
					this.SendPropertyChanging();
					this._NgayNhap = value;
					this.SendPropertyChanged("NgayNhap");
					this.OnNgayNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNguyenLieu_tblCongThuc", Storage="_tblCongThucs", ThisKey="MaNL", OtherKey="MaNL")]
		public EntitySet<tblCongThuc> tblCongThucs
		{
			get
			{
				return this._tblCongThucs;
			}
			set
			{
				this._tblCongThucs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblCongThucs(tblCongThuc entity)
		{
			this.SendPropertyChanging();
			entity.tblNguyenLieu = this;
		}
		
		private void detach_tblCongThucs(tblCongThuc entity)
		{
			this.SendPropertyChanging();
			entity.tblNguyenLieu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblNhanVien")]
	public partial class tblNhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNV;
		
		private string _TenNV;
		
		private string _DiaChi;
		
		private string _SDT;
		
		private int _MaLoaiNV;
		
		private string _TaiKhoan;
		
		private EntitySet<tblHoaDon> _tblHoaDons;
		
		private EntitySet<tblTaiKhoan> _tblTaiKhoans;
		
		private EntityRef<tblLoaiNhanVien> _tblLoaiNhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(int value);
    partial void OnMaNVChanged();
    partial void OnTenNVChanging(string value);
    partial void OnTenNVChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnMaLoaiNVChanging(int value);
    partial void OnMaLoaiNVChanged();
    partial void OnTaiKhoanChanging(string value);
    partial void OnTaiKhoanChanged();
    #endregion
		
		public tblNhanVien()
		{
			this._tblHoaDons = new EntitySet<tblHoaDon>(new Action<tblHoaDon>(this.attach_tblHoaDons), new Action<tblHoaDon>(this.detach_tblHoaDons));
			this._tblTaiKhoans = new EntitySet<tblTaiKhoan>(new Action<tblTaiKhoan>(this.attach_tblTaiKhoans), new Action<tblTaiKhoan>(this.detach_tblTaiKhoans));
			this._tblLoaiNhanVien = default(EntityRef<tblLoaiNhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNV", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenNV
		{
			get
			{
				return this._TenNV;
			}
			set
			{
				if ((this._TenNV != value))
				{
					this.OnTenNVChanging(value);
					this.SendPropertyChanging();
					this._TenNV = value;
					this.SendPropertyChanged("TenNV");
					this.OnTenNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Char(100) NOT NULL", CanBeNull=false)]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiNV", DbType="Int NOT NULL")]
		public int MaLoaiNV
		{
			get
			{
				return this._MaLoaiNV;
			}
			set
			{
				if ((this._MaLoaiNV != value))
				{
					if (this._tblLoaiNhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiNVChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiNV = value;
					this.SendPropertyChanged("MaLoaiNV");
					this.OnMaLoaiNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="Char(100) NOT NULL", CanBeNull=false)]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					this.OnTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoan = value;
					this.SendPropertyChanged("TaiKhoan");
					this.OnTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNhanVien_tblHoaDon", Storage="_tblHoaDons", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<tblHoaDon> tblHoaDons
		{
			get
			{
				return this._tblHoaDons;
			}
			set
			{
				this._tblHoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNhanVien_tblTaiKhoan", Storage="_tblTaiKhoans", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<tblTaiKhoan> tblTaiKhoans
		{
			get
			{
				return this._tblTaiKhoans;
			}
			set
			{
				this._tblTaiKhoans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblLoaiNhanVien_tblNhanVien", Storage="_tblLoaiNhanVien", ThisKey="MaLoaiNV", OtherKey="MaLoaiNV", IsForeignKey=true)]
		public tblLoaiNhanVien tblLoaiNhanVien
		{
			get
			{
				return this._tblLoaiNhanVien.Entity;
			}
			set
			{
				tblLoaiNhanVien previousValue = this._tblLoaiNhanVien.Entity;
				if (((previousValue != value) 
							|| (this._tblLoaiNhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblLoaiNhanVien.Entity = null;
						previousValue.tblNhanViens.Remove(this);
					}
					this._tblLoaiNhanVien.Entity = value;
					if ((value != null))
					{
						value.tblNhanViens.Add(this);
						this._MaLoaiNV = value.MaLoaiNV;
					}
					else
					{
						this._MaLoaiNV = default(int);
					}
					this.SendPropertyChanged("tblLoaiNhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblHoaDons(tblHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.tblNhanVien = this;
		}
		
		private void detach_tblHoaDons(tblHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.tblNhanVien = null;
		}
		
		private void attach_tblTaiKhoans(tblTaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.tblNhanVien = this;
		}
		
		private void detach_tblTaiKhoans(tblTaiKhoan entity)
		{
			this.SendPropertyChanging();
			entity.tblNhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblTaiKhoan")]
	public partial class tblTaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNV;
		
		private string _TenDN;
		
		private string _MatKhau;
		
		private string _Quyen;
		
		private EntityRef<tblNhanVien> _tblNhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(int value);
    partial void OnMaNVChanged();
    partial void OnTenDNChanging(string value);
    partial void OnTenDNChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnQuyenChanging(string value);
    partial void OnQuyenChanged();
    #endregion
		
		public tblTaiKhoan()
		{
			this._tblNhanVien = default(EntityRef<tblNhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._tblNhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDN", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TenDN
		{
			get
			{
				return this._TenDN;
			}
			set
			{
				if ((this._TenDN != value))
				{
					this.OnTenDNChanging(value);
					this.SendPropertyChanging();
					this._TenDN = value;
					this.SendPropertyChanged("TenDN");
					this.OnTenDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quyen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Quyen
		{
			get
			{
				return this._Quyen;
			}
			set
			{
				if ((this._Quyen != value))
				{
					this.OnQuyenChanging(value);
					this.SendPropertyChanging();
					this._Quyen = value;
					this.SendPropertyChanged("Quyen");
					this.OnQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblNhanVien_tblTaiKhoan", Storage="_tblNhanVien", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public tblNhanVien tblNhanVien
		{
			get
			{
				return this._tblNhanVien.Entity;
			}
			set
			{
				tblNhanVien previousValue = this._tblNhanVien.Entity;
				if (((previousValue != value) 
							|| (this._tblNhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblNhanVien.Entity = null;
						previousValue.tblTaiKhoans.Remove(this);
					}
					this._tblNhanVien.Entity = value;
					if ((value != null))
					{
						value.tblTaiKhoans.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(int);
					}
					this.SendPropertyChanged("tblNhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
